memory_mb: 200000 # max_memory
threads: 32 # n_cores

min_length: 35
min_quality: 25

classification_software: "centrifuge" # either kraken2 or centrifuge 
classification_index: "/global/home/users/jieruixu/jieruixu/sediment_dna/peerj_replication/centrifuge/nt"
taxID: "/global/home/users/jieruixu/jieruixu/sediment_dna/sedimix/final_pipeline/temp/primates_taxids.csv" # primate

use_snp_panel: False 
ref_genome: "/global/home/users/jieruixu/jieruixu/sediment_dna/sedimix/reference_data/human/hg19.fa"
# snp_panel_bed: "/global/home/users/jieruixu/jieruixu/sediment_dna/sedimix/final_pipeline/pendant_2023/probes_reich_n3_b8_CONTROL_BV09-BV09.bed" 

calculate_from_mapdamage: True
lineage_sites: "/global/home/users/jieruixu/jieruixu/sediment_dna/sedimix/final_pipeline/pendant_2023/probes_reich_n3_b8_CONTROL_BV09-BV09.transformed.txt"
types: "hominin_informative"

to_clean: False
keep_non_hominin_reads: True 